import type { Metadata } from "next";
import { Noto_Sans_Display, Playfair_Display } from "next/font/google";
import "./globals.css";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

const noto_Sans_Display: NextFontWithVariable = Noto_Sans_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto_Sans_Display",
});

const playfair: NextFontWithVariable = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html
      lang="en"
      className={`${noto_Sans_Display.variable} ${playfair.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
