import type { Metadata } from "next";
import { Playfair_Display, Bebas_Neue } from "next/font/google";
import "./globals.css";

const playfair_dislpay = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
});

const bebas_neue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair_dislpay.className} ${bebas_neue.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
