import type { Metadata } from "next";
import "./globals.css";
import { space_mono } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${space_mono.className} antialiased bg-zinc-800`}>
        {children}
      </body>
    </html>
  );
}
