// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	EventID      int32
	Name         string
	StartGgID    int64
	TournamentID int32
	CreatedAt    pgtype.Timestamp
}

type Match struct {
	MatchID   int32
	EventID   int32
	CreatedAt pgtype.Timestamp
}

type MatchCharacter struct {
	MatchID     int32
	PlayerID    int32
	GameNumber  int32
	Win         bool
	PreRating   pgtype.Numeric
	CharacterID int32
}

type MatchSlot struct {
	MatchID  int32
	PlayerID int32
	Score    int32
	Win      bool
	R        pgtype.Numeric
	Rd       pgtype.Numeric
	Sigma    pgtype.Numeric
	Delta    pgtype.Numeric
}

type Placement struct {
	EventID   int32
	PlayerID  int32
	Placement int32
}

type Player struct {
	PlayerID        int32
	Name            string
	FirstAppearance pgtype.Date
	CreatedAt       pgtype.Timestamp
}

type PlayerAlias struct {
	PlayerID  int32
	StartGgID int64
}

type Tournament struct {
	TournamentID int32
	Name         string
	Postcode     pgtype.Text
	EndAt        pgtype.Date
	CountryCode  string
	Slug         string
	CreatedAt    pgtype.Timestamp
}
