// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacterData = `-- name: CreateCharacterData :one
INSERT INTO match_characters (match_id, player_id, game_number, win, pre_rating, character_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING match_id, player_id, game_number, win, pre_rating, character_id
`

type CreateCharacterDataParams struct {
	MatchID     int32
	PlayerID    int32
	GameNumber  int32
	Win         bool
	PreRating   pgtype.Numeric
	CharacterID int32
}

func (q *Queries) CreateCharacterData(ctx context.Context, arg CreateCharacterDataParams) (MatchCharacter, error) {
	row := q.db.QueryRow(ctx, createCharacterData,
		arg.MatchID,
		arg.PlayerID,
		arg.GameNumber,
		arg.Win,
		arg.PreRating,
		arg.CharacterID,
	)
	var i MatchCharacter
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.GameNumber,
		&i.Win,
		&i.PreRating,
		&i.CharacterID,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events ( name, start_gg_id, tournament_id)
VALUES ($1,$2,$3)
RETURNING event_id, name, start_gg_id, tournament_id, created_at
`

type CreateEventParams struct {
	Name         string
	StartGgID    int64
	TournamentID int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.Name, arg.StartGgID, arg.TournamentID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.Name,
		&i.StartGgID,
		&i.TournamentID,
		&i.CreatedAt,
	)
	return i, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (event_id)
VALUES ($1)
RETURNING match_id, event_id, created_at
`

func (q *Queries) CreateMatch(ctx context.Context, eventID int32) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, eventID)
	var i Match
	err := row.Scan(&i.MatchID, &i.EventID, &i.CreatedAt)
	return i, err
}

const createMatchSlot = `-- name: CreateMatchSlot :one
INSERT INTO match_slot (match_id, player_id, score, win, r, rd, sigma, delta)
VALUES ($1, $2, $3, $4, $5,$6,$7,$8)
RETURNING match_id, player_id, score, win, r, rd, sigma, delta
`

type CreateMatchSlotParams struct {
	MatchID  int32
	PlayerID int32
	Score    int32
	Win      bool
	R        pgtype.Numeric
	Rd       pgtype.Numeric
	Sigma    pgtype.Numeric
	Delta    pgtype.Numeric
}

func (q *Queries) CreateMatchSlot(ctx context.Context, arg CreateMatchSlotParams) (MatchSlot, error) {
	row := q.db.QueryRow(ctx, createMatchSlot,
		arg.MatchID,
		arg.PlayerID,
		arg.Score,
		arg.Win,
		arg.R,
		arg.Rd,
		arg.Sigma,
		arg.Delta,
	)
	var i MatchSlot
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.Score,
		&i.Win,
		&i.R,
		&i.Rd,
		&i.Sigma,
		&i.Delta,
	)
	return i, err
}

const createPlacement = `-- name: CreatePlacement :one
INSERT INTO placements (event_id, player_id, placement)
VALUES ($1, $2, $3)
RETURNING event_id, player_id, placement
`

type CreatePlacementParams struct {
	EventID   int32
	PlayerID  int32
	Placement int32
}

func (q *Queries) CreatePlacement(ctx context.Context, arg CreatePlacementParams) (Placement, error) {
	row := q.db.QueryRow(ctx, createPlacement, arg.EventID, arg.PlayerID, arg.Placement)
	var i Placement
	err := row.Scan(&i.EventID, &i.PlayerID, &i.Placement)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one

WITH new_player AS (
  INSERT INTO players (name, first_appearance)
  VALUES ($1, $2)
  RETURNING player_id, name, first_appearance, created_at
),
alias_insert AS (
  INSERT INTO player_aliases (player_id, start_gg_id)
  SELECT player_id, $3 FROM new_player
)
SELECT player_id, name, first_appearance, created_at FROM new_player
`

type CreatePlayerParams struct {
	Name            string
	FirstAppearance pgtype.Date
	StartGgID       int64
}

type CreatePlayerRow struct {
	PlayerID        int32
	Name            string
	FirstAppearance pgtype.Date
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.Name, arg.FirstAppearance, arg.StartGgID)
	var i CreatePlayerRow
	err := row.Scan(
		&i.PlayerID,
		&i.Name,
		&i.FirstAppearance,
		&i.CreatedAt,
	)
	return i, err
}

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (name, postcode, end_at, country_code, slug)
VALUES ($1, $2, $3, $4, $5)
RETURNING tournament_id, name, postcode, end_at, country_code, slug, created_at
`

type CreateTournamentParams struct {
	Name        string
	Postcode    pgtype.Text
	EndAt       pgtype.Date
	CountryCode string
	Slug        string
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament,
		arg.Name,
		arg.Postcode,
		arg.EndAt,
		arg.CountryCode,
		arg.Slug,
	)
	var i Tournament
	err := row.Scan(
		&i.TournamentID,
		&i.Name,
		&i.Postcode,
		&i.EndAt,
		&i.CountryCode,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getLastTournament = `-- name: GetLastTournament :one
SELECT tournament_id, name, postcode, end_at, country_code, slug, created_at FROM tournaments ORDER BY end_at DESC LIMIT 1
`

func (q *Queries) GetLastTournament(ctx context.Context) (Tournament, error) {
	row := q.db.QueryRow(ctx, getLastTournament)
	var i Tournament
	err := row.Scan(
		&i.TournamentID,
		&i.Name,
		&i.Postcode,
		&i.EndAt,
		&i.CountryCode,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getMostRecentMatchForPlayer = `-- name: GetMostRecentMatchForPlayer :one
SELECT ms.match_id, ms.player_id, ms.score, ms.win, ms.r, ms.rd, ms.sigma, ms.delta
FROM match_slot ms
JOIN matches m ON ms.match_id = m.match_id
WHERE ms.player_id = $1
ORDER BY m.created_at DESC
LIMIT 1
`

func (q *Queries) GetMostRecentMatchForPlayer(ctx context.Context, playerID int32) (MatchSlot, error) {
	row := q.db.QueryRow(ctx, getMostRecentMatchForPlayer, playerID)
	var i MatchSlot
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.Score,
		&i.Win,
		&i.R,
		&i.Rd,
		&i.Sigma,
		&i.Delta,
	)
	return i, err
}

const getPlayerAliase = `-- name: GetPlayerAliase :one
SELECT player_id, start_gg_id FROM player_aliases WHERE start_gg_id = $1
`

func (q *Queries) GetPlayerAliase(ctx context.Context, startGgID int64) (PlayerAlias, error) {
	row := q.db.QueryRow(ctx, getPlayerAliase, startGgID)
	var i PlayerAlias
	err := row.Scan(&i.PlayerID, &i.StartGgID)
	return i, err
}

const getPlayerFromAlias = `-- name: GetPlayerFromAlias :one
SELECT player_id, name, first_appearance, created_at FROM players WHERE player_id = (SELECT player_id FROM player_aliases WHERE start_gg_id = $1)
`

// This query will fail if the start_gg_id does not exist
func (q *Queries) GetPlayerFromAlias(ctx context.Context, startGgID int64) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerFromAlias, startGgID)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.Name,
		&i.FirstAppearance,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayer = `-- name: getPlayer :one
SELECT player_id, name, first_appearance, created_at FROM players WHERE player_id = $1
`

func (q *Queries) getPlayer(ctx context.Context, playerID int32) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, playerID)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.Name,
		&i.FirstAppearance,
		&i.CreatedAt,
	)
	return i, err
}
