name: Build and Deploy

on:
  push:
    branches:
      - main
      - v2

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  STARTGG_API_TOKEN: ${{ secrets.STARTGG_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     known_hosts: "unnecessary"

      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # - name: Deploy with rsync
      #   run: rsync -avz --delete . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIRECTORY }}

      # - name: Execute SSH commmands on remote server
      #   uses: JimCronqvist/action-ssh@master
      #   with:
      #     hosts: ${{ secrets.USERNAME }}@${{ secrets.HOST }}
      #     privateKey: ${{ secrets.PRIVATE_KEY }}
      #     command: pm2 restart melee-ranked
