// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"database/sql"
	"time"
)

type Event struct {
	EventID      int32
	Name         string
	StartGgID    int32
	TournamentID int32
}

type Match struct {
	MatchID   int32
	EventID   int32
	StartGgID string
}

type MatchSlot struct {
	MatchID  int32
	PlayerID int32
	Score    int32
	Win      bool
}

type Placement struct {
	EventID   int32
	PlayerID  int32
	Placement int32
}

type Player struct {
	PlayerID        int32
	Name            string
	FirstAppearance time.Time
}

type PlayerAlias struct {
	PlayerID  int32
	StartGgID int32
}

type Rating struct {
	PlayerID int32
	Rating   float64
	Rd       float64
	Sigma    float64
	Date     time.Time
}

type Tournament struct {
	TournamentID int32
	Name         string
	Postcode     sql.NullString
	EndAt        time.Time
	Slug         string
}
